runtime: go121

main: ./cmd/server

runtime_config:
  gce_metadata_path: /app/gce_metadata

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  PORT: 8080
  ENV: production
  GCP_PROJECT_ID: govoice-406116
  GIN_MODE: release
